### ISSUE TITLE
need help registering some native tokens

### ISSUE THREAD

**Issue by Adahandles** [input-output-hk/metadata-registry-testnet#488]
HOSKDOG (HKDG) 9560f81458d28648d9261d180ee2b10afcf6b2305909d367f8f9f0ad
Trump Coin (TRC) 640edd900e0ef3ef44d634d77dae25c24154424591de008b0920aaae
EAT CORN (CORN )34a2bcd51c9780440664300e56e98e0503e7df79d39f42a874df5539

**Comment by AndrewWestberg** [comment]
@Adahandles . Please open up a separate pull request for each of these tokens. I assume they are on one of the test networks? (preprod/preview)
